version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    command:
      - "-requests_per_second=10"
      - "-addr=envoy:8080"
      - "-operation_millis=10"
    restart: on-failure:3
    depends_on:
      - server
      - dogstatsd
  envoy:
    image: envoyproxy/envoy-dev:latest
    deploy:
      replicas: 10
    volumes:
      - ./apps/client/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901-9999:9901"
  server: &server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    # ports:
    #   - "50051:50051"
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.01"
          memory: "50M"
    depends_on:
      - dogstatsd
  # slow_server:
  #   <<: *server
  #   command:
  #     - "-add_latency_millis=1"
  #   deploy:
  #     replicas: 1
  #   extends:
  #     service: server
  dogstatsd:
    image: datadog/dogstatsd:latest
    env_file:
      - .env
