version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    command:
      - "-requests_per_second=10"
    restart: on-failure:3
    depends_on:
      - server
      - dogstatsd
    deploy:
      replicas: 1
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    # ports:
    #   - "50051:50051"
    deploy:
      replicas: 10
    depends_on:
      - dogstatsd
  dogstatsd:
    image: datadog/dogstatsd:latest
    env_file:
      - .env
