version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    command:
      - "-requests_per_second=10"
    restart: on-failure:3
    depends_on:
      - server
      - dogstatsd
    deploy:
      replicas: 1
    networks:
      - default
  server: &server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    # ports:
    #   - "50051:50051"
    deploy:
      replicas: 10
    depends_on:
      - dogstatsd
    networks:
      - default
      - backend
  slow_server:
    <<: *server
    command:
      - "-add_latency_millis=10"
    deploy:
      replicas: 1
  dogstatsd:
    image: datadog/dogstatsd:latest
    env_file:
      - .env
    networks:
      - default

networks:
  backend:
    driver: bridge
