// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.26.1
// source: lib/proto/dummy/dummy.proto

package dummy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoSomethingRequest) Reset() {
	*x = DoSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_dummy_dummy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSomethingRequest) ProtoMessage() {}

func (x *DoSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_dummy_dummy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSomethingRequest.ProtoReflect.Descriptor instead.
func (*DoSomethingRequest) Descriptor() ([]byte, []int) {
	return file_lib_proto_dummy_dummy_proto_rawDescGZIP(), []int{0}
}

type DoSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoSomethingResponse) Reset() {
	*x = DoSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_dummy_dummy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSomethingResponse) ProtoMessage() {}

func (x *DoSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_dummy_dummy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSomethingResponse.ProtoReflect.Descriptor instead.
func (*DoSomethingResponse) Descriptor() ([]byte, []int) {
	return file_lib_proto_dummy_dummy_proto_rawDescGZIP(), []int{1}
}

var File_lib_proto_dummy_dummy_proto protoreflect.FileDescriptor

var file_lib_proto_dummy_dummy_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x75, 0x6d, 0x6d,
	0x79, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x6f, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x6f,
	0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x56, 0x0a, 0x0c, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x6f, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x12, 0x19, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x44, 0x6f, 0x53, 0x6f, 0x6d, 0x65, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x75,
	0x6d, 0x6d, 0x79, 0x2e, 0x44, 0x6f, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_proto_dummy_dummy_proto_rawDescOnce sync.Once
	file_lib_proto_dummy_dummy_proto_rawDescData = file_lib_proto_dummy_dummy_proto_rawDesc
)

func file_lib_proto_dummy_dummy_proto_rawDescGZIP() []byte {
	file_lib_proto_dummy_dummy_proto_rawDescOnce.Do(func() {
		file_lib_proto_dummy_dummy_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_proto_dummy_dummy_proto_rawDescData)
	})
	return file_lib_proto_dummy_dummy_proto_rawDescData
}

var file_lib_proto_dummy_dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_proto_dummy_dummy_proto_goTypes = []interface{}{
	(*DoSomethingRequest)(nil),  // 0: dummy.DoSomethingRequest
	(*DoSomethingResponse)(nil), // 1: dummy.DoSomethingResponse
}
var file_lib_proto_dummy_dummy_proto_depIdxs = []int32{
	0, // 0: dummy.DummyService.DoSomething:input_type -> dummy.DoSomethingRequest
	1, // 1: dummy.DummyService.DoSomething:output_type -> dummy.DoSomethingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_proto_dummy_dummy_proto_init() }
func file_lib_proto_dummy_dummy_proto_init() {
	if File_lib_proto_dummy_dummy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_proto_dummy_dummy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_dummy_dummy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_proto_dummy_dummy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_proto_dummy_dummy_proto_goTypes,
		DependencyIndexes: file_lib_proto_dummy_dummy_proto_depIdxs,
		MessageInfos:      file_lib_proto_dummy_dummy_proto_msgTypes,
	}.Build()
	File_lib_proto_dummy_dummy_proto = out.File
	file_lib_proto_dummy_dummy_proto_rawDesc = nil
	file_lib_proto_dummy_dummy_proto_goTypes = nil
	file_lib_proto_dummy_dummy_proto_depIdxs = nil
}
